### ISSUE TITLE
segmentation faults on some variables/frequencies

### ISSUE THREAD

**Issue by wdulac** [IS-ENES-Data/QA-DKRZ#22]
While running qa-dkrz-0.6.7-66 from conda, some files unexpectedly cause a segmentation fault.

For instance, all files of daily means of mrfso (Soil Frozen Water Content) have the `segmentation fault` conclusion, while monthly and 6-hourly means do not.

The files raising this message do not present any issues in any obvious ways, i.e they can be handled by the CDO tools collection, plotted with ncview etc.

Also, another install running qa-dkrz-0.6.7-31 doesn't have this problem. 

Here's the config section for the 0.6.7-66 install:
```
# Log-file created by QA-DKRZ
configuration:
 command-line:  /path/to/qa-dkrz.py -f task_file_AAD12-ALDERA
 options:
  APPLY_MAXIMUM_DATE_RANGE: t
  ARITHMETIC_MEAN: t
  CFG_FILE: /home/USERNAME/.qa-dkrz/config.txt
  CF_AREA_TYPES: cf-area-type-table.txt
  CF_CHECK_LIST: CF_check-list.conf
  CF_FOLLOW_RECOMMENDATIONS: t
  CF_NOTE: {plev,height,CF_5h,D}
  CF_STANDARD_NAMES: cf-standard-name-table.xml
  CF_STD_REGION_NAMES: cf-standardized-region-list.txt
  CF_VERSION: std-name:v70,10December2019|area-type:v9,07August2018
  CLEAR: 
  CONDA: True
  CONDA_PATH: /path/to/conda
  CONDA_QA_ENV: /path/to/qa-dkrz/conda/env
  CORDEX_VERSION: IS-ENES-Data.github.io:master-e52685a
  CS_NO_HISTORY: t
  CT_PATH_INDEX: [2, 3, 4, 7, 8, 11]
  CT_PATH_INDEX_MAX: 11
  CURR_DIR: /home/USERNAME/QA-DKRZ
  DEFAULT_VALID_MAX: 1E+17
  DEFAULT_VALID_MIN: -1E-15
  DRS_PATH_BASE: CORDEX
  FILE_NAME_SEP: _
  FILE_NAME_VAR_INDEX: 0
  FREQ_INDEX_FNAME: 7
  HARD_SLEEP_PERIOD: 10
  IGNORE_REFERENCE_DATE: t
  IGNORE_REF_DATE_ACROSS_EXP: t
  LOCK_PATH_LIST: []
  LOCK_VAR_LIST: []
  LOG_FILE_INDEX: [1, 2, 5, 3]
  LOG_FNAME_DIR: /home/USERNAME/QA-DKRZ/AAD12-ALDERA/check_logs
  LOG_INDEX_MAX: 11
  LOG_PATH_INDEX: [2, 3, 4, 7, 5, 8, 11]
  MAIL: mailx
  NEVER_BREAK_SESSION: t
  NEXT_CF_UPDATE: 20200108+1
  NEXT_CORDEX_UPDATE: 20200108+1
  NUM_EXEC_THREADS: 8
  OUTLIER_TEST: ['N10', 'P0.01', 'M3', 'L3']
  PATH_SEP: /
  PROJECT: CORDEX
  PROJECT_DATA: /path/to/data
  PROJECT_TABLE_PREFIX: pt_
  QA_CHECK_LIST: CORDEX_check-list.conf
  QA_CONF: task_file_AAD12-ALDERA,/path/to/QA_TABLES/tables/projects/CORDEX/CORDEX_qa.conf
  QA_EXEC_HOSTS: hostname
  QA_HOST: hostname
  QA_RESULTS: /home/USERNAME/QA-DKRZ/AAD12-ALDERA/
  QA_SRC: /path/to/conda/envs/qa-dkrz/opt/qa-dkrz
  QA_TABLES: /path/to/QA_TABLES
  QA_VERSION: qa-dkrz-0.6.7-66|std-name:v70,10December2019|area-type:v9,07August2018|IS-ENES-Data.github.io:master-e52685a
  QUERY_EMPTY_DIR: t
  QUERY_EMPTY_FILE: t
  QUERY_NON_NC_FILE: t
  QUERY_ONLY_NC: t
  REATTEMPT_LIMIT: 5
  SELECT_PATH_LIST: []
  SELECT_VAR_LIST: []
  SESSION: 2020-02-05T14:21:27
  SESSION_LOGDIR: /home/USERNAME/QA-DKRZ/AAD12-ALDERA/session_logs/2020-02-05T14:21:27
  SLEEP_PERIOD: 300
  TABLES:
   - CF_AREA_TYPES: cf-area-type-table.txt
   - CF_CHECK_LIST: CF_check-list.conf
   - CF_STANDARD_NAMES: cf-standard-name-table.xml
   - CF_STD_REGION_NAMES: cf-standardized-region-list.txt
   - PROJECT_TABLE_PREFIX: pt_
   - QA_CHECK_LIST: CORDEX_check-list.conf
   - TABLE_DRS_CV: CORDEX_DRS_CV.csv
   - TABLE_GCM_NAME: CORDEX_GCMModelName.txt
   - TABLE_RCM_NAME: CORDEX_RCMs_ToU.txt
   - TABLE_VAR_REQ: CORDEX_variables_requirement_table.csv
  TASK: task_file_AAD12-ALDERA
  UDUNITS2_XML_PATH: /path/to/conda/envs/qa-dkrz/share/udunits/udunits2.xml
  UPDATE: frozen
  ZOMBIE_LIMIT: 3600
start:
 date: 2020-02-05T14:26:45
 qa-revision: qa-dkrz-0.6.7-66|std-name:v70,10December2019|area-type:v9,07August2018|IS-ENES-Data.github.io:master-e52685a
```

You can contact me by mail should you want access to said files.

--
William
