### ISSUE TITLE
Could not create a consistency-check table

### ISSUE THREAD

**Issue by JavierDiezSierra** [IS-ENES-Data/QA-DKRZ#24]
I am starting to work with the qa-dkrz and it returns me the following error for most of CORDEX simulations i have tried:

```
 - event:
    - annotation: Could not create a consistency-check table.
    - impact: L1
    - tag: IE_1
```

Could you explain me what does it mean?

Thank you very much.
